#!/usr/bin/env python3
#
# This file is part of the Robotic Observatory Control Kit (rockit)
#
# rockit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# rockit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rockit.  If not, see <http://www.gnu.org/licenses/>.

"""Daemon for controlling a multi-channel focus controller via Pyro"""

import argparse
import datetime
import queue
import re
import threading
import traceback
import sys
import serial
import Pyro4
from rockit.common import log
from rockit.common.helpers import pyro_client_matches
from rockit.focuser import CommandStatus, Config, FocuserStatus


class FocuserDaemon:
    """Daemon interface for multi-channel focuser"""
    def __init__(self, config):
        self.wait_condition = threading.Condition()
        self._config = config

        channels = range(1, config.channels + 1)
        regex = ','.join([rf'T{c}=(?P<T{c}>[+-]\d{{6}}),C{c}=(?P<C{c}>[+-]\d{{6}})' for c in channels])
        self._regex = re.compile(regex)

        self._state_lock = threading.Lock()
        self._state_date = datetime.datetime.min
        self._current_steps = [0 for _ in channels]
        self._target_steps = [0 for _ in channels]

        self._fans_enabled = False
        self._temperature = {key: None for key in config.temperature_probes}
        self._temperature_index = 0

        self._comm_lock = threading.Lock()
        self._command_queue = queue.Queue()
        self._result_queue = queue.Queue()
        self._move_complete_condition = threading.Condition()
        self._port = None

        threading.Thread(target=self.__run, daemon=True).start()

    def _open_connection(self):
        """
        Opens the serial connection to the focuser.
        Returns CommandStatus reflecting result
        """
        if self._port is not None:
            return CommandStatus.NotDisconnected

        try:
            port = serial.Serial(self._config.serial_port,
                                 self._config.serial_baud,
                                 timeout=self._config.serial_timeout)
            log.info(self._config.log_name, 'connected to controller')

            # Flush any stale state
            port.flushInput()
            port.flushOutput()

            with self._state_lock:
                self._port = port

            # Refresh state before considering the connection valid
            self._update_state()

            return CommandStatus.Succeeded
        except Exception as exception:
            print(f'Failed to read serial port ({exception})')
            if self._port is not None:
                self._port.close()
                self._port = None

            return CommandStatus.Failed

    def _close_connection(self):
        """
        Closes the serial connection to the focuser.
        Returns CommandStatus reflecting result
        """
        with self._state_lock:
            if self._port is None:
                return CommandStatus.NotConnected

            try:
                if self._port is not None:
                    self._port.close()
                    self._port = None
                return CommandStatus.Succeeded
            except Exception as exception:
                print(f'Failed to close serial port ({exception})')
                self._port = None
                return CommandStatus.Failed

    def _update_temperatures(self):
        """Poll the temperature of one-wire probes"""
        # Measurements take ~1 second per probe, so we round-robin polling the probes
        if self._port is None or not self._config.temperature_probes:
            return

        probe_name = list(self._config.temperature_probes.keys())[self._temperature_index]
        address = self._config.temperature_probes[probe_name]['address']

        if self._port.write(f'@{address}\n'.encode('ascii')) != 18:
            raise serial.SerialException('Failed to send temperature query command')

        response = self._port.readline().decode('ascii').strip()
        if response != '?' and response != 'FAILED':
            self._temperature[probe_name] = float(response)

        self._temperature_index = (self._temperature_index + 1) % len(self._config.temperature_probes)

    def _update_state(self):
        """Request and parse the status of the focus controller"""
        if self._port is None:
            return

        if self._port.write('?\n'.encode('ascii')) != 2:
            raise serial.SerialException('Failed to send stepper query command')

        response = self._port.readline().decode('ascii').strip()
        match = self._regex.match(response)
        if not match:
            raise serial.SerialException(f'Failed to parse status result: `{response}`')

        with self._state_lock:
            self._state_date = datetime.datetime.utcnow()
            for i in range(self._config.channels):
                self._current_steps[i] = int(match.group(f'C{i + 1}'))
                self._target_steps[i] = int(match.group(f'T{i + 1}'))

        if self._port.write('#\n'.encode('ascii')) != 2:
            raise serial.SerialException('Failed to send fan query command')

        response = self._port.readline().decode('ascii').strip()
        self._fans_enabled = response == '1'

    def process_request(self, request, data):
        """
        Process a command sent by the user
        Returns a CommandStatus that is pushed to the results queue
        """
        if self._port is None:
            return CommandStatus.NotConnected

        if request == 'fans':
            command = f'#{1 * data}\n'
        else:
            # Only stop is valid when moving
            if request != 'stop':
                i = data[0] - 1
                if self._current_steps[i] != self._target_steps[i]:
                    return CommandStatus.Blocked

            if request == 'stop':
                command = f'{data[0]}S\n'
            elif request == 'zero':
                command = f'{data[0]}Z\n'
            elif request == 'set':
                self._target_steps[data[0] - 1] = data[1]
                command = f'{data[0]}{data[1]:+07d}\n'
            elif request == 'offset':
                self._target_steps[data[0] - 1] += data[1]
                command = f'{data[0]}{self._target_steps[data[0] - 1]:+07d}\n'
            else:
                print(f'Unknown request `{request}`')
                return CommandStatus.Failed

        if self._port.write(command.encode('ascii')) != len(command):
            print('Failed to send command')
            return CommandStatus.Failed

        if self._port.readline().decode('ascii').strip() != '$':
            return CommandStatus.Failed

        return CommandStatus.Succeeded

    def __run(self):
        """Background thread managing communication over the serial connection"""
        delay = self._config.idle_loop_delay
        while True:
            try:
                request, data = self._command_queue.get(timeout=delay)
            except queue.Empty:
                request, data = None, None

            if request == 'connect':
                self._result_queue.put(self._open_connection())
                continue

            if request == 'disconnect':
                self._result_queue.put(self._close_connection())
                continue

            result = CommandStatus.NotConnected
            was_moving = any(self._current_steps[i] != t for i, t in enumerate(self._target_steps))
            is_moving = False
            try:
                # Refresh the state to ensure a valid view of the controller state before returning
                self._update_state()
                self._update_temperatures()

                is_moving = self._port is not None and \
                    any(self._current_steps[i] != t for i, t in enumerate(self._target_steps))

                if request is not None:
                    result = self.process_request(request, data)

                    # Refresh the state to ensure a valid view of the controller state before returning
                    self._update_state()

            except Exception as exception:
                with self._state_lock:
                    if self._port is not None:
                        self._port.close()
                        self._port = None

                print(f'Failed to read serial port ({exception})')
                log.error(self._config.log_name, 'Lost serial connection')
                traceback.print_exc(file=sys.stdout)
            finally:
                if request is not None:
                    self._result_queue.put(result)

                if was_moving and not is_moving:
                    with self._move_complete_condition:
                        self._move_complete_condition.notify_all()

                delay = self._config.moving_loop_delay if is_moving else self._config.idle_loop_delay

    @Pyro4.expose
    def report_status(self):
        """Returns a dictionary containing the current focuser state"""
        with self._state_lock:
            data = {
                'date': datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ'),
                'status': FocuserStatus.Disabled if self._port is None else FocuserStatus.Active
            }

            if self._port is not None:
                data.update({
                    'fans_enabled': self._fans_enabled,
                    'temperature': self._temperature
                })

                for i in range(self._config.channels):
                    c = i + 1
                    data.update({
                        f'target_steps_{c}': self._target_steps[i],
                        f'current_steps_{c}': self._current_steps[i],
                        f'moving_{c}': self._target_steps[i] != self._current_steps[i]
                    })

            return data

    @Pyro4.expose
    def temperature_labels(self):
        """Query the labels associated with the temperature probes"""
        return {k: v['label'] for k, v in self._config.temperature_probes.items()}

    @Pyro4.expose
    def set_focus(self, channel, steps, offset=False):
        """Request a focuser channel to move a specific step position"""
        if not pyro_client_matches(self._config.control_ips):
            return CommandStatus.InvalidControlIP

        if channel < 1 or channel > self._config.channels:
            return CommandStatus.InvalidChannel

        with self._comm_lock:
            self._command_queue.put(('offset' if offset else 'set', (channel, steps)))
            result = self._result_queue.get()

        if result != CommandStatus.Succeeded:
            return result

        start = datetime.datetime.utcnow()
        i = channel - 1

        while True:
            with self._move_complete_condition:
                self._move_complete_condition.wait(1)

            if self._current_steps[i] == self._target_steps[i]:
                break

            if self._port is None:
                return CommandStatus.Failed

            if (datetime.datetime.utcnow() - start).total_seconds() > self._config.move_timeout:
                return CommandStatus.Failed

        return CommandStatus.Succeeded

    @Pyro4.expose
    def reset_home_position(self, channel):
        """Request a focuser channel to reset its home position to its current position"""
        if not pyro_client_matches(self._config.control_ips):
            return CommandStatus.InvalidControlIP

        if channel < 1 or channel > self._config.channels:
            return CommandStatus.InvalidChannel

        with self._comm_lock:
            self._command_queue.put(('zero', (channel, None)))
            return self._result_queue.get()

    @Pyro4.expose
    def enable_fans(self, enabled):
        """Turn OTA fans on or off"""
        if not pyro_client_matches(self._config.control_ips):
            return CommandStatus.InvalidControlIP

        with self._comm_lock:
            self._command_queue.put(('fans', enabled))
            return self._result_queue.get()

    @Pyro4.expose
    def stop_channel(self, channel):
        """Stop any in progress movement"""
        if not pyro_client_matches(self._config.control_ips):
            return CommandStatus.InvalidControlIP

        if channel < 1 or channel > self._config.channels:
            return CommandStatus.InvalidChannel

        with self._comm_lock:
            self._command_queue.put(('stop', (channel, None)))
            return self._result_queue.get()

    @Pyro4.expose
    def initialize(self):
        """Connects to the focuser hardware"""
        if not pyro_client_matches(self._config.control_ips):
            return CommandStatus.InvalidControlIP

        with self._comm_lock:
            self._command_queue.put(('connect', None))
            return self._result_queue.get()

    @Pyro4.expose
    def shutdown(self):
        """Disconnects from the focuser hardware"""
        if not pyro_client_matches(self._config.control_ips):
            return CommandStatus.InvalidControlIP

        with self._comm_lock:
            self._command_queue.put(('disconnect', None))
            return self._result_queue.get()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Focus Server')
    parser.add_argument('config', help='Path to configuration json file')
    args = parser.parse_args()
    _config = Config(args.config)
    _config.daemon.launch(FocuserDaemon(_config))
